/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package K_Means;

import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Random;


/**
 *
 * @author leona
 */
public class Ventana extends javax.swing.JFrame {

    //cositas 
        
        private int x,y;
        private int clases=1,k=1,items=100;
        private K_Means algoritmo;
        private Random r;
        private ArrayList<Color> colores;
        
    //constructor 
    public Ventana() {
        
        initComponents();
        initComponents2();
        this.x = -1;
        this.y = -1;
        
        r= new Random();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plano = new javax.swing.JPanel();
        fieldK = new javax.swing.JTextField();
        fieldItems = new javax.swing.JTextField();
        fieldClases = new javax.swing.JTextField();
        btnDate = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnInicializa = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        plano.setBackground(new java.awt.Color(255, 204, 204));

        javax.swing.GroupLayout planoLayout = new javax.swing.GroupLayout(plano);
        plano.setLayout(planoLayout);
        planoLayout.setHorizontalGroup(
            planoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );
        planoLayout.setVerticalGroup(
            planoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        fieldK.setText("5");
        fieldK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldKActionPerformed(evt);
            }
        });

        fieldItems.setText("7");
        fieldItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldItemsActionPerformed(evt);
            }
        });

        fieldClases.setText("3");

        btnDate.setText("date");
        btnDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDateActionPerformed(evt);
            }
        });

        jLabel1.setText("K");

        jLabel2.setText("items de clase");

        jLabel3.setText("clases");

        btnInicializa.setText("crea plano");
        btnInicializa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicializaActionPerformed(evt);
            }
        });

        btnLimpiar.setText("limpia");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnInicializa)
                    .addComponent(plano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(fieldClases, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(25, 25, 25))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fieldItems, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldK, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap()))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDate)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimpiar)
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(plano, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(fieldItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldClases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnLimpiar)
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDate)
                    .addComponent(btnInicializa))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void initComponents2(){
        
        colores = new ArrayList();
        
        plano.addMouseListener(new java.awt.event.MouseAdapter() {

            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt){
           
                formMouseClicked(evt);            
            }
        
        });
                
    }//initComponents2
    
    
    
    private void formMouseClicked(java.awt.event.MouseEvent evt){
    
           this.x = evt.getX();
           this.y = evt.getY();
           algoritmo.x = this.x;
           algoritmo.y = this.y;
           
           
           
           paintPunto(plano.getGraphics());
           //plano.updateUI();
          
    }//formMouseClicked
    
   
        @Override
    public void update(Graphics g) {
        super.update(g);

    }
    public void paintXY(Graphics g){
        
        int alto_plano = plano.getHeight(); //alto
        int ancho_plano = plano.getWidth(); //ancho

        g.drawLine(ancho_plano/2, 0, ancho_plano/2, alto_plano);
        g.drawLine(0, alto_plano/2, ancho_plano, alto_plano/2);
        g.drawLine(50, 100, 50, 100);
    }
    
    public void generaClases(){
    
        this.k = Integer.parseInt(fieldK.getText());
        this.clases = Integer.parseInt(fieldClases.getText());
        this.items = Integer.parseInt(fieldItems.getText());
        algoritmo = new K_Means(k,clases,items,this.x,this.y,plano.getWidth(),plano.getHeight());
        
    }
    public void printClases(){
        
        
        System.out.println("k: " + algoritmo.k);
        System.out.println("clases: " + algoritmo.clases);
        System.out.println("items: " + algoritmo.items);
        System.out.println("x: " + algoritmo.x);
        System.out.println("y: " + algoritmo.y);
        
    }
    
    public void paintClases(Graphics g){
        
        for (int i=0; i<clases;i++){
            Color c = new Color(r.nextInt(255),r.nextInt(255),r.nextInt(255));
            colores.add(c);
            g.setColor(c);
            for(int n=0;n<items;n++){
                
                g.fillOval(algoritmo.itemsArray.get((items*i)+n).x,algoritmo.itemsArray.get((items*i)+n).y,8,8);
            
            }
        
        }
        
    }
    
    public void paintPunto(Graphics g){
        
        if(this.x >=0 && this.y>=0){
        
            g.setColor(Color.BLUE);
            g.fillOval(this.x,this.y,10,10);

        }
        
    }
    public void clasifica(Graphics g){
        
        if(this.x >=0 && this.y>=0){
        
            g.setColor(colores.get(algoritmo.pertenece));
            g.fillOval(this.x,this.y,10,10);

        }
        
    }
    
    private void fieldItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldItemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldItemsActionPerformed

    private void btnDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDateActionPerformed
        // TODO add your handling code here:
        
        algoritmo.calculaCercano();
        //JOptionPane.showMessageDialog(this, " Pertenece a la clase: " + colores.get(algoritmo.pertenece));
        clasifica(plano.getGraphics());
    }//GEN-LAST:event_btnDateActionPerformed

    private void btnInicializaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicializaActionPerformed
        // TODO add your handling code here:
        paintXY(plano.getGraphics());
        generaClases();
        printClases();
        paintClases(plano.getGraphics());
        
        //btnInicializa.setEnabled(false);
    }//GEN-LAST:event_btnInicializaActionPerformed

    private void fieldKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldKActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        update(this.getGraphics());
        this.colores.clear();
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
            //</editor-fold>
            
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDate;
    private javax.swing.JButton btnInicializa;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JTextField fieldClases;
    private javax.swing.JTextField fieldItems;
    private javax.swing.JTextField fieldK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel plano;
    // End of variables declaration//GEN-END:variables
}
